### ISSUE TITLE
Chez Scheme Support Tracking

### ISSUE THREAD

**Issue by 6cdh** [6cdh/tree-sitter-scheme#1]
This is a tracking issue for [Chez Scheme](https://github.com/cisco/ChezScheme) support.
The specific syntax can be found at [Chez Scheme Syntax](https://cisco.github.io/ChezScheme/csug9.5/intro.html#./intro:h1).

- [ ] extended identifier
  - [ ] Identifiers can start with digit, or one of `.+-` as long as it is not parsed as a number
  - [ ] `{` or `}` are identifiers
  - [ ] escape with `\` or `|`
  - [ ] enclose between `#{` and `}`
- [ ] extra radixes
- [ ] character
  - [ ] `#\bel`, `#\ls`, `#\nel`, `#\nul`, `#\rubout`, `#\vt`, `#\vtab`
  - [ ] octal character - `#\` followed by a three octal digit sequence
- [ ] fixnum vector
- [ ] Shared and cyclic structure
- [ ] `$primitive` form
- [ ] boolean - case insensitive `#true`, `#false`
