### ISSUE TITLE
Chicken Scheme Support Tracking

### ISSUE THREAD

**Issue by 6cdh** [6cdh/tree-sitter-scheme#3]
This is a tracking issue for [Chicken Scheme](https://call-cc.org/) support.
The specific syntax can be found at [Chicken Scheme Syntax](https://wiki.call-cc.org/man/5/Extensions%20to%20the%20standard).

Chicken Scheme support R<sup>5</sup>RS with extension:

- [ ] Identifier between `|`
- [x] `[` and `{` are alternative as `(`
- [ ] character
  - [ ] `#\xXX` where `XX` specifies the character code in hexadecimal
  - [ ] `#\uXXXX` or `#\UXXXXXXXX`
  - [ ] `#\tab #\linefeed #\return #\alarm #\vtab #\nul #\page #\esc #\delete #\backspace`
- [ ] escape sequence in string `\n\r\b\t\v\a\f\xXX\uXXXX\UXXXXXXXX`
- [x] multiline comment between `#|` and `|#`
- [x] expression comment `#;`
- [ ] abbreviation `#, #$`
- [ ] blob literal `#${ ... }`
- [ ] keyword `#:`
- [ ] here string `#<<`
- [ ] multiline string with embedded expression `#<#`
- [ ] foreign declare `#> ... <#`
- [ ] band `#!`
- [ ] case sensitive `#cs`, `#ci`
- [ ] conditional expansion `#+`
